mqtt:
  username: mqttPubClient
  password: 123456
  cleanSession: false
  serverURIs:
  - tcp://iot.eclipse.org:1883
  async: true
  completionTimeout: 20000
  keepAliveInterval: 30
  clientId: mqttPubClient
  defaultQos: 1